- name: Linux Troubleshooting setup script
  hosts: all
  roles:
    # - root_password_break  
    # - package_management
    # - user
    # - network_management
    # - lvm
    # - luks
    - apache
    # - samba
    # - mysql
    # - ssh

  # tasks:
  #   - name: Print network interfaces
  #     ansible.builtin.debug:
  #       msg: "Network Interface: {{ item }}"
  #     loop: "{{ ansible_facts.interfaces }}"