- name: Linux Troubleshooting setup script
  hosts: all
  roles:
    - root_password_break  
    - package_management
    - apache
    - samba
    - ssh

  # tasks:
  # - name: Restaring server
  #   reboot: