- name: Linux Troubleshooting setup script
  hosts: all
  become: yes
  roles:
    # - root_password_break  
    # - package_management
    # - user
    - network_management
    # - lvm
    # - luks
    # - apache
    # - samba
    # - ssh

  # tasks:
  #   - name: Print network interfaces
  #     ansible.builtin.debug:
  #       msg: "{{ ansible_facts.interfaces[0] }}"
  #     loop: "{{ ansible_facts.interfaces }}"