---
- name: Preparing servera.lab.com for exam lab...
  hosts: all
  become: true
  vars:
    repostate: enabled
  roles:
    - rootpasswd-q
  # tasks:
  #   - name: Printing facts
  #     debug:
  #       var: ansible_facts.default_ipv4