---
# tasks file for ./roles/network_management
 - name: Try nmcli add team - conn_name only & ip4 gw4
   nmcli:
    conn_name: "{{ ansible_facts.interfaces[2] }}"
    dns4: 8.8.8.8
    state: present

#  - name: Activating New connection
#    shell: nmcli connection up my-eth1